### ISSUE TITLE
Unicode first/last_name fails authenticate method

### ISSUE THREAD

**Issue by danra** [ThatGreenSpace/django-freshdesk#10]
The problem is in views.py:28, in this line:
`full_name = '{0} {1}'.format(first_name, last_name) if first_name or last_name else username`

In case first_name or last_name are uncidoe, this throws a UnicodeEncodeError, e.g.
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 0: ordinal not in range(128)
`

Hopefully, u'{0} {1}'.format(...) in this line would solve the issue, though I suspect other strings in the function would also have to be modified to handle unicode names correctly.

This is really urgent :0 It's a pretty bad experience for a user who needs support and gets an error, trying to log in into the Freshdesk support portal...

Using Python 2.7.11.

Thanks!
Dan

**Comment by arescope** [comment]
Done!
