### ISSUE TITLE
Django versions in Tox environment matrix

### ISSUE THREAD

**Issue by suriya** [ThatGreenSpace/django-freshdesk#8]
Here is Django's current list of supported versions: https://www.djangoproject.com/download/#supported-versions

There are two unsupported Django versions (1.6 and 1.7) in https://github.com/ThatGreenSpace/django-freshdesk/blob/d40529708a937ab25e702cab5d541ee1e0ab11c3/tox.ini Supported Django version 1.9 is not being tested.

Should the file be cleaned up to match Django's supported versions?

**Comment by arescope** [comment]
yes totally.

**Comment by arescope** [comment]
I already did and merged

**Comment by suriya** [comment]
In https://github.com/ThatGreenSpace/django-freshdesk/blob/bebe13688a1f9eef765aaa3a72060c3d79b5dc89/setup.py#L51 `install_requires=['Django>1.5,<1.9',],` should change to allow the use of Django 1.9.
